services:
  db:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: teste4
        MYSQL_DATABASE: teste3
        MYSQL_USER: teste2
        MYSQL_PASSWORD: teste1
    ports:
      - "3306:3306" 
    volumes:
      - db:/data/mysql 
volumes:
  db: