services:
  db:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_DATABASE: teste3
        POSTGRES_USER: teste2
        POSTGRES_PASSWORD: teste1
    ports:
      - "5432:5434" 
    volumes:
      - db:/data/mysql 
volumes:
  db: