services:
  db:
    image: postgres:latest
    restart: always
    environment:
          POSTGRES_DB: 'teste3'
          POSTGRES_USER: ${{ secrets.AZURE_USER_POSTGRES }}
          POSTGRES_PASSWORD: ${{ secrets.AZURE_PASSWORD_POSTGRES }}
    ports:
      - "5434:5432" 
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
