services:
  db:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_DATABASE: teste3
        POSTGRES_USER: teste2
        POSTGRES_PASSWORD: teste1
    ports:
      - "5434:5432" 
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
